name: superhero_app
description: "SuperHero Search."
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  http: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/hero.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
